path_classifiers:
  docs:
    - "LICENSE*"
    - "*.md"
    - "*.html"
  ci:
    - ".travis.yml"
    - ".github"
    - ".lgtm.yml"
  generated:
    - exclude: "build/sources"
extraction:
  java:
    index:
      java_version: 8
      gradle:
        version: "4.10.3"
